name: Test and Release

on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'
    paths-ignore:
      - '**/*.md'
      - LICENSE
  pull_request:

jobs:
  test-bun:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
    - run: bun run test:bun
    - run: bun i --frozen-lockfile
    - run: bun run lint
    - run: bun run test:typescript

  test-deno:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: denoland/setup-deno@v2
      with:
        deno-version: latest
    - run: deno run test:deno

  test-node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16, 18, 20, 22]
        os: [ubuntu-latest, mac-latest, windows-latest]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm run test:node

  release:
    if: ${{ github.ref_name == 'master' }}
    needs:
    - test-bun
    - test-deno
    - test-node
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4
    - uses: prantlf/publish-release-action@v1
      with:
        no-archives: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
